// <auto-generated />
namespace Stevens_Kevin_HW7A.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _4models : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_4models));
        
        string IMigrationMetadata.Id
        {
            get { return "201712010001478_4models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
