// <auto-generated />
namespace Stevens_Kevin_HW7A.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dateaddd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dateaddd));
        
        string IMigrationMetadata.Id
        {
            get { return "201711282303542_dateaddd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
